# TF Regression Project

California Housing Data

This data set contains information about all the block groups in California from the 1990 Census. In this sample a block group on average includes 1425.5 individuals living in a geographically compact area. 

The task is to aproximate the median house value of each block from the values of the rest of the variables. 

Dataset -  http://www.liaad.up.pt/~ltorgo/Regression/DataSets.html.
 

The Features:
 
* housingMedianAge: continuous. 
* totalRooms: continuous. 
* totalBedrooms: continuous. 
* population: continuous. 
* households: continuous. 
* medianIncome: continuous. 
* medianHouseValue: continuous. 

** Import data **

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv('cal_housing_clean.csv')

In [3]:
housing.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  medianHouseValue  
0        8.3252          452600.0  
1        8.3014          358500.0  
2        7.2574          352100.0  
3        5.6431          341300.0  
4        3.8462          342200.0

In [4]:
housing.describe().transpose()
 

count           mean            std         min  \
housingMedianAge  20640.0      28.639486      12.585558      1.0000   
totalRooms        20640.0    2635.763081    2181.615252      2.0000   
totalBedrooms     20640.0     537.898014     421.247906      1.0000   
population        20640.0    1425.476744    1132.462122      3.0000   
households        20640.0     499.539680     382.329753      1.0000   
medianIncome      20640.0       3.870671       1.899822      0.4999   
medianHouseValue  20640.0  206855.816909  115395.615874  14999.0000   

                          25%          50%           75%          max  
housingMedianAge      18.0000      29.0000      37.00000      52.0000  
totalRooms          1447.7500    2127.0000    3148.00000   39320.0000  
totalBedrooms        295.0000     435.0000     647.00000    6445.0000  
population           787.0000    1166.0000    1725.00000   35682.0000  
households           280.0000     409.0000     605.00000    6082.0000  
medianIncome           2.5634       3.5348       4.74325      15.0001  
medianHouseValue  119600.0000  179700.0000  264725.00000  500001.0000

In [5]:
x_data = housing.drop(['medianHouseValue'],axis=1)

In [6]:
y_val = housing['medianHouseValue']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(x_data,y_val,test_size=0.3,random_state=101)

### Scale the Feature Data

** Use sklearn preprocessing to create a MinMaxScaler for the feature data. 

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler()

In [11]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [12]:
X_train = pd.DataFrame(data=scaler.transform(X_train),columns = X_train.columns,index=X_train.index)
X_test = pd.DataFrame(data=scaler.transform(X_test),columns = X_test.columns,index=X_test.index)

### Create Feature Columns

** Create the necessary tf.feature_column objects for the estimator **

In [13]:
housing.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [14]:
import tensorflow as tf

C:\Users\Rahman\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [ ]:
** Create continuous feature_columns for the continuous values using numeric_column **

In [15]:
age = tf.feature_column.numeric_column('housingMedianAge')
rooms = tf.feature_column.numeric_column('totalRooms')
bedrooms = tf.feature_column.numeric_column('totalBedrooms')
pop = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
income = tf.feature_column.numeric_column('medianIncome')

In [16]:
feat_cols = [ age,rooms,bedrooms,pop,households,income]

** Create the input function for the estimator object. **

In [17]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train ,batch_size=10,num_epochs=1000,
                                            shuffle=True)

** Create the estimator model, Use a DNNRegressor **
** Create 3 layer and 6 neoron for each layer **

In [18]:
model = tf.estimator.DNNRegressor(hidden_units=[6,6,6],feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Rahman\\AppData\\Local\\Temp\\tmprwf343qu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002AA71C652E8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


#### ** Train the model for 10000 steps. **

In [19]:
model.train(input_fn=input_func,steps=10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Rahman\AppData\Local\Temp\tmprwf343qu\model.ckpt.
INFO:tensorflow:loss = 374342600000.0, step = 1
INFO:tensorflow:global_step/sec: 238.969
INFO:tensorflow:loss = 630055500000.0, step = 101 (0.429 sec)
INFO:tensorflow:global_step/sec: 299.738
INFO:tensorflow:loss = 751589500000.0, step = 201 (0.323 sec)
INFO:tensorflow:global_step/sec: 344.994
INFO:tensorflow:loss = 718195800000.0, step = 301 (0.290 sec)
INFO:tensorflow:global_step/sec: 348.74
INFO:tensorf

INFO:tensorflow:global_step/sec: 329.675
INFO:tensorflow:loss = 47860564000.0, step = 6701 (0.303 sec)
INFO:tensorflow:global_step/sec: 315.633
INFO:tensorflow:loss = 164883780000.0, step = 6801 (0.301 sec)
INFO:tensorflow:global_step/sec: 346.757
INFO:tensorflow:loss = 194452520000.0, step = 6901 (0.308 sec)
INFO:tensorflow:global_step/sec: 312.432
INFO:tensorflow:loss = 72617640000.0, step = 7001 (0.299 sec)
INFO:tensorflow:global_step/sec: 328.829
INFO:tensorflow:loss = 74157060000.0, step = 7101 (0.304 sec)
INFO:tensorflow:global_step/sec: 281.322
INFO:tensorflow:loss = 73833650000.0, step = 7201 (0.372 sec)
INFO:tensorflow:global_step/sec: 265.284
INFO:tensorflow:loss = 98270740000.0, step = 7301 (0.362 sec)
INFO:tensorflow:global_step/sec: 321.481
INFO:tensorflow:loss = 117290254000.0, step = 7401 (0.309 sec)
INFO:tensorflow:global_step/sec: 322.823
INFO:tensorflow:loss = 121553986000.0, step = 7501 (0.311 sec)
INFO:tensorflow:global_step/sec: 334.93
INFO:tensorflow:loss = 708586

** Create prediction input function then use .predict method off estimator model to create a list or predictions on test data. **

In [20]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(
      x=X_test,
      batch_size=10,
      num_epochs=1,
      shuffle=False)

In [21]:
pred_gen = model.predict(predict_input_func)

In [22]:
predictions = list(pred_gen)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Rahman\AppData\Local\Temp\tmprwf343qu\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


### ** Calculate the RMSE. **

In [23]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['predictions'])

In [24]:
final_preds

[array([230098.81], dtype=float32),
 array([279058.7], dtype=float32),
 array([221632.84], dtype=float32),
 array([181812.77], dtype=float32),
 array([252920.23], dtype=float32),
 array([202886.7], dtype=float32),
 array([231670.6], dtype=float32),
 array([207920.27], dtype=float32),
 array([210539.58], dtype=float32),
 array([172476.38], dtype=float32),
 array([207936.72], dtype=float32),
 array([229437.16], dtype=float32),
 array([194442.06], dtype=float32),
 array([177847.31], dtype=float32),
 array([260515.11], dtype=float32),
 array([172942.7], dtype=float32),
 array([205513.05], dtype=float32),
 array([184604.72], dtype=float32),
 array([179393.38], dtype=float32),
 array([224531.81], dtype=float32),
 array([170126.88], dtype=float32),
 array([232190.62], dtype=float32),
 array([216054.27], dtype=float32),
 array([168928.4], dtype=float32),
 array([194115.62], dtype=float32),
 array([254339.8], dtype=float32),
 array([189276.67], dtype=float32),
 array([150516.8], dtype=float32),

In [25]:
from sklearn.metrics import mean_squared_error

In [26]:
print('MSE : {}'.format(mean_squared_error(y_test,final_preds)**0.5))

MSE : 103843.55741876525
